### ISSUE TITLE
species_info error - dimensions dropped

### ISSUE THREAD

**Issue by johnbaums** [AtlasOfLivingAustralia/ALA4R#11]
For some taxa (maybe largely constrained to those without "proper" guids?), `species_info` fails to return the record.

e.g. for http://bie.ala.org.au/ws/species/ALA_Caladenia_cardiochila 

```
> species_info(guid='ALA_Caladenia_cardiochila')
Error in subset.default(out$classification, select = tempcols) : 
  argument "subset" is missing, with no default
> species_info('Caladenia cardiochila')
Error in subset.default(out$classification, select = tempcols) : 
  argument "subset" is missing, with no default
```

Similarly for ALA_Pterostylis_squamata.

Seems that in `species_info`, `out[[k]] = out[[k]][, tempcols]` needs to be `out[[k]] = out[[k]][, tempcols, drop=FALSE]` to accommodate these, since e.g. `family` is the only field present in `$classification`.

**Comment by raymondben** [comment]
Thanks, well spotted, fixed in v1.17. I hadn't previously seen taxa with that sort of improper classificaton. For those taxa, the returned classification is just a string, not a data.frame. I've avoided the error, but it does mean that the returned `result$classification` object is just a string, not a data.frame as it is for taxa with proper classifications. But I don't see any easy way of fixing this at the R end, it would require the underlying ALA taxonomic information to be corrected.

**Comment by johnbaums** [comment]
Nice one, thanks for the explanation.

**Comment by raymondben** [comment]
Minor update in v1.18: the `result$classification` object in these cases will now be a data.frame (though with only one column and one row). Note that this change may affect other elements of the `result` object that were previously single-element string or numeric, because they will now also be left as single-element data.frames.
