### ISSUE TITLE
search_names and hyphenation

### ISSUE THREAD

**Issue by johnbaums** [AtlasOfLivingAustralia/ALA4R#4]
Something weird is going on with hyphenation in `search_names`. Take for example the species [_Acaena novae-zelandiae_](http://bie.ala.org.au/species/urn:lsid:biodiversity.org.au:apni.taxon:376906):

`search_names('Acaena novae zelandiae')` returns 

      searchTerm               name                     commonName                                       rank      guid                                            
    1 "Acaena novae zelandiae" "Acaena novae-zelandiae" "Biddy Biddy, Biddy-widdy, Bidgee-widgee, Buzzy" "species" "urn:lsid:biodiversity.org.au:apni.taxon:376906"

but `search_names('Acaena novae-zelandiae')` returns an empty matrix.

**Comment by Tasilee** [comment]
I note that 

search_fulltext("Acaena novae zelandiae") = search_fulltext("Acaena novae-zelandiae") = 
search_partial_name("Acaena novae zelandiae") = search_partial_name("Acaena novae-zelandiae") = 
search_partial_name("Acaena novae")

**Comment by nickdos** [comment]
@djtfmartin for the rewrite - you might want to check the SOLR query analyser for the search_names field. It looks like the indexing analyser is removing hyphens but the query one is not. They should be using the same analyser, from memory.

**Comment by raymondben** [comment]
Fixed in v1.11. It was a problem with slightly over-zealous cleaning of the search term before passing it to the web service. Other than trimming whitespaces, we now pass the search term unchanged.

`search_names('Acaena novae-zelandiae')`

  searchTerm               name                     commonName                                       rank      guid                                            
1 "Acaena novae-zelandiae" "Acaena novae-zelandiae" "Biddy Biddy, Biddy-widdy, Bidgee-widgee, Buzzy" "species" "urn:lsid:biodiversity.org.au:apni.taxon:376906"
